# Usar uma imagem base do Node.js
FROM node:14

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos do projeto
COPY . /app

# Instalar as dependências
RUN npm install

# Expor a porta 3000
EXPOSE 3000

# Comando para rodar o servidor
CMD ["node", "server.js"]
